INSERT INTO Genres(GenreId,[Name],CreatedBy)VALUES
(144, 'Personal Finance','Migration'),
(151,	'Locally Focused','Migration'),
(68,	'TV & Film','Migration'),
(127,	'Technology','Migration'),
(135,	'True Crime','Migration'),
(100,	'Arts','Migration'),
(93,	'Business','Migration'),
(133,	'Comedy','Migration'),
(111,	'Education','Migration'),
(168,	'Fiction','Migration'),
(117,	'Government','Migration'),
(88,	'Health & Fitness','Migration'),
(125,	'History','Migration'),
(132,	'Kids & Family','Migration'),
(82,	'Leisure','Migration'),
(134,	'Music','Migration'),
(99,	'News','Migration'),
(69,	'Religion & Spirituality','Migration'),
(107,	'Science','Migration'),
(122,	'Society & Culture','Migration'),
(77,	'Sports','Migration');
