INSERT INTO Regions(RegionId,[Name],CreatedBy)VALUES
('ae', 'United Arab Emirates','Migration'),
('ag', 'Antigua and Barbuda','Migration'),
('ai', 'Anguilla','Migration'),
('al', 'Albania','Migration'),
('am', 'Armenia','Migration'),
('ao', 'Angola','Migration'),
('ar', 'Argentina','Migration'),
('at', 'Austria','Migration'),
('au', 'Australia','Migration'),
('az', 'Azerbaijan','Migration'),
('bb', 'Barbados','Migration'),
('bd', 'Bangladesh','Migration'),
('be', 'Belgium','Migration'),
('bf', 'Burkina-Faso','Migration'),
('bg', 'Bulgaria','Migration'),
('bh', 'Bahrain','Migration'),
('bj', 'Benin','Migration'),
('bm', 'Bermuda','Migration'),
('bn', 'Brunei Darussalam','Migration'),
('bo', 'Bolivia','Migration'),
('br', 'Brazil','Migration'),
('bs', 'Bahamas','Migration'),
('bt', 'Bhutan','Migration'),
('bw', 'Botswana','Migration'),
('by', 'Belarus','Migration'),
('bz', 'Belize','Migration'),
('ca', 'Canada','Migration'),
('ch', 'Switzerland','Migration'),
('cl', 'Chile','Migration'),
('cn', 'China','Migration'),
('co', 'Colombia','Migration'),
('cr', 'Costa Rica','Migration'),
('cv', 'Cape Verde','Migration'),
('cy', 'Cyprus','Migration'),
('cz', 'Czech Republic','Migration'),
('de', 'Germany','Migration'),
('dk', 'Denmark','Migration'),
('dm', 'Dominica','Migration'),
('do', 'Dominican Republic','Migration'),
('dz', 'Algeria','Migration'),
('ec', 'Ecuador','Migration'),
('ee', 'Estonia','Migration'),
('eg', 'Egypt','Migration'),
('es', 'Spain','Migration'),
('fi', 'Finland','Migration'),
('fj', 'Fiji','Migration'),
('fr', 'France','Migration'),
('gb', 'United Kingdom','Migration'),
('gd', 'Grenada','Migration'),
('gh', 'Ghana','Migration'),
('gm', 'Gambia','Migration'),
('gr', 'Greece','Migration'),
('gt', 'Guatemala','Migration'),
('gw', 'Guinea Bissau','Migration'),
('gy', 'Guyana','Migration'),
('hk', 'Hong Kong','Migration'),
('hn', 'Honduras','Migration'),
('hr', 'Croatia','Migration'),
('hu', 'Hungary','Migration'),
('id', 'Indonesia','Migration'),
('ie', 'Ireland','Migration'),
('il', 'Israel','Migration'),
('in', 'India','Migration'),
('is', 'Iceland','Migration'),
('it', 'Italy','Migration'),
('jm', 'Jamaica','Migration'),
('jo', 'Jordan','Migration'),
('jp', 'Japan','Migration'),
('ke', 'Kenya','Migration'),
('kg', 'Krygyzstan','Migration'),
('kh', 'Cambodia','Migration'),
('kr', 'South Korea','Migration'),
('kw', 'Kuwait','Migration'),
('ky', 'Cayman Islands','Migration'),
('kz', 'Kazakhstan','Migration'),
('la', 'Laos','Migration'),
('lb', 'Lebanon','Migration'),
('lc', 'Saint Lucia','Migration'),
('lk', 'Sri Lanka','Migration'),
('lr', 'Liberia','Migration'),
('lt', 'Lithuania','Migration'),
('lu', 'Luxembourg','Migration'),
('lv', 'Latvia','Migration'),
('md', 'Moldova','Migration'),
('mg', 'Madagascar','Migration'),
('mk', 'Macedonia','Migration'),
('ml', 'Mali','Migration'),
('mn', 'Mongolia','Migration'),
('mo', 'Macau','Migration'),
('mr', 'Mauritania','Migration'),
('ms', 'Montserrat','Migration'),
('mt', 'Malta','Migration'),
('mu', 'Mauritius','Migration'),
('mw', 'Malawi','Migration'),
('mx', 'Mexico','Migration'),
('my', 'Malaysia','Migration'),
('mz', 'Mozambique','Migration'),
('na', 'Namibia','Migration'),
('ne', 'Niger','Migration'),
('ng', 'Nigeria','Migration'),
('ni', 'Nicaragua','Migration'),
('nl', 'Netherlands','Migration'),
('no', 'Norway','Migration'),
('np', 'Nepal','Migration'),
('nz', 'New Zealand','Migration'),
('om', 'Oman','Migration'),
('pa', 'Panama','Migration'),
('pe', 'Peru','Migration'),
('pg', 'Papua New Guinea','Migration'),
('ph', 'Philippines','Migration'),
('pk', 'Pakistan','Migration'),
('pl', 'Poland','Migration'),
('pt', 'Portugal','Migration'),
('pw', 'Palau','Migration'),
('py', 'Paraguay','Migration'),
('qa', 'Qatar','Migration'),
('ro', 'Romania','Migration'),
('ru', 'Russia','Migration'),
('sa', 'Saudi Arabia','Migration'),
('sb', 'Soloman Islands','Migration'),
('sc', 'Seychelles','Migration'),
('se', 'Sweden','Migration'),
('sg', 'Singapore','Migration'),
('si', 'Slovenia','Migration'),
('sk', 'Slovakia','Migration'),
('sl', 'Sierra Leone','Migration'),
('sn', 'Senegal','Migration'),
('so', 'Somalia','Migration'),
('sr', 'Suriname','Migration'),
('sv', 'El Salvador','Migration'),
('sz', 'Swaziland','Migration'),
('td', 'Chad','Migration'),
('th', 'Thailand','Migration'),
('tj', 'Tajikistan','Migration'),
('tm', 'Turkmenistan','Migration'),
('tn', 'Tunisia','Migration'),
('tr', 'Turkey','Migration'),
('tw', 'Taiwan','Migration'),
('tz', 'Tanzania','Migration'),
('ua', 'Ukraine','Migration'),
('ug', 'Uganda','Migration'),
('us', 'United States','Migration'),
('uy', 'Uruguay','Migration'),
('uz', 'Uzbekistan','Migration'),
('ve', 'Venezuela','Migration'),
('vg', 'British Virgin Islands','Migration'),
('vn', 'Vietnam','Migration'),
('ye', 'Yemen','Migration'),
('za', 'South Africa','Migration'),
('zw', 'Zimbabwe','Migration');